window.onload = function () {

    let headerHeight = document.getElementById('header').offsetHeight;
    const marginTop = 50;
    document.getElementsByClassName('article')[0].style.marginTop = (headerHeight + marginTop + "px");
    
    document.getElementById("for-invalid").innerHTML = '<div id="font-size"><p class="for-invalid-paragraph">Размер шрифта:</p><div onclick="smallFontSize()" tabindex="1" id="small-size"><p id="small-font">А</p></div><div onclick="middleFontSize()" tabindex="2" id="middle-size"><p id="middle-font">А</></div><div onclick="highFontSize()" tabindex="3" id="high-size"><p id="high-font">А</p></div></div><div id="color-scheme"><p class="for-invalid-paragraph">Цветовая схема:</p><div onclick="colorChange(\'#ffffffff\' ,\'#000\')" tabindex="4" id="white-black"><p class="color-paragraph">А</p></div><div onclick="colorChange(\'#000\' ,\'#fff\')" tabindex="5" id="black-white"><p class="color-paragraph">А</p></div><div tabindex="6" onclick="colorChange(\'#063462\' ,\'#9ed1ff\')" id="blue"><p class="color-paragraph">А</p></div><div onclick="colorChange(\'#59422e\' ,\'#f7f3d6\')" tabindex="7" id="brown"><p class="color-paragraph">А</p></div><div onclick="colorChange(\'#a9dd38\' ,\'#59422e\')" tabindex="8" id="green-brown"><p class="color-paragraph">А</p></div></div><div id="img-on-off"><p class="for-invalid-paragraph">Изображения:</p><div class="margin-left"><div onclick="imagesOnOff(\'on\')"><input tabindex="9" type="radio" name="img-on-off" checked id="on"><label for="on">Вкл</label></div><div onclick="imagesOnOff(\'off\')"><input tabindex="10" type="radio" name="img-on-off" id="off"><label for="off">Выкл</label></div></div></div><div id="font"><p class="for-invalid-paragraph">Шрифт:</p><div class="margin-left"><p id="arial-click" class=\'paragraph-js\' onclick="fontChange(\'Arial, Helvetica, sans-serif\')" style="font-family: Arial, Helvetica, sans-serif;">Без засечек</p><p id="times-new-roman-click" class=\'paragraph-js\' onclick="fontChange(\'TimesNewRoman, Times, serif\')" style="font-family: Times New Roman, Times, serif;">С засечками</p></div></div><div id="font-interval"><p class="for-invalid-paragraph">Межбуквенный интервал:</p><div class="margin-left"><p id="min-spacing" onclick="letterSpacingChange(\'\')" class=\'paragraph-js\'>Стандартный</p><p id="middle-spacing" onclick="letterSpacingChange(\'3px\')" class=\'paragraph-js\' style="letter-spacing: 3px;">Средний</p><p id="max-spacing" onclick="letterSpacingChange(\'4px\')" class=\'paragraph-js\' style="letter-spacing: 4px;">Большой</p></div></div><div><p onclick="invalidReset()" id="delete-invalid">Сброс настроек</p></div>';
    document.getElementsByClassName('nav-menu-container')[0].innerHTML = '<img id="closeButton" class="iconJS open_close_icon" src="/test/icons8-удалить-50.png"><div class="nav-menu-block"><a class="nav-menu-link" href="">Автобусы. Подвоз детей</a><a class="nav-menu-link" href="">Адаптированные основные общеобразовательные программы на 2020-2021 учебный год</a><a class="nav-menu-link" href="">Аннотации к рабочим программам 2020-2021</a><a class="nav-menu-link" href="">Архив</a><a class="nav-menu-link" href="">Аттестация ГИА, ОГЭ 2020</a><a class="nav-menu-link" href="">Безопасность</a><a class="nav-menu-link" href="">Бессмертный полк</a><a class="nav-menu-link" href="">Воспитательная работа</a><a class="nav-menu-link" href="">Всероссийская олимпиада школьников</a><a class="nav-menu-link" href="">Горячая линия</a><a class="nav-menu-link" href="">Дистанционное обучение</a><a class="nav-menu-link" href="">Документы по ведению сайта</a><a class="nav-menu-link" href="">Дополнительное образование</a><a class="nav-menu-link" href="">Информация для родителей</a><a class="nav-menu-link" href="">Информация для учащихся</a><a class="nav-menu-link" href="">Информация для учителей</a><a class="nav-menu-link" href="">Информация по ФГОС</a><a class="nav-menu-link" href="">История школы</a><a class="nav-menu-link" href="">Карта сайта</a><a class="nav-menu-link" href="">Клуб "Импульс"</a></div><div class="nav-menu-block"><a class="nav-menu-link" href="">Методическая работа</a><a class="nav-menu-link" href="">Независимая оценка качества образования</a><a class="nav-menu-link" href="/pages/news/news.html">Новости</a><a class="nav-menu-link" href="">Обратная связь, контакты</a><a class="nav-menu-link" href="">Обучение лиц с ОВЗ и инвалидов</a><a class="nav-menu-link" href="">Основные общеобразовательные программы на 2020-2021 учебный год</a><a class="nav-menu-link" href="">Отчет о самообследовании</a><a class="nav-menu-link" href="">Охрана здоровья обучающихся</a><a class="nav-menu-link" href="">Персональные данные</a><a class="nav-menu-link" href="">Пожарная безопасность</a><a class="nav-menu-link" href="">Портал персонифицированного дополнительного образования области</a><a class="nav-menu-link" href="">Прием в 1 и 10 классы</a><a class="nav-menu-link" href="">Прием детей в школу</a><a class="nav-menu-link" href="">Профилактика коррупции</a><a class="nav-menu-link" href="">Сведения об образовательной организации</a><a class="nav-menu-link" href="/pages/tochka_rosta/tochka-rosta.html">Точка Роста</a><a class="nav-menu-link" href="">Управляющий Совет школы</a><a class="nav-menu-link" href="">Школьная служба медиации "Контакт"</a><a class="nav-menu-link" href="">Электронный журнал</a></div>';



    openButton.onclick = openNavMenu;
    closeButton.onclick = closeNavMenu;

    document.getElementById('invalid_image').onclick = invalid;
}